# Generated by Django 5.0.2 on 2024-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PART', 'Parts'), ('SHP', 'Second Hand Parts'), ('CON', 'Contract')], default='PART', max_length=4),
        ),
    ]
