# Generated by Django 5.0.2 on 2024-06-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CN', 'China'), ('JP', 'Japan'), ('IR', 'Iran'), ('DE', 'Germany'), ('SE', 'Sweden'), ('IT', 'Italy'), ('CH', 'Switzerland'), ('NO', 'Norway'), ('CA', 'Canada'), ('FI', 'Finland'), ('CN', 'China'), ('RU', 'Russia')], default='PART', max_length=255),
        ),
    ]
