# Generated by Django 5.0.2 on 2024-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
