# Generated by Django 5.0.2 on 2024-06-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_items',
        ),
    ]
