# Generated by Django 5.0.2 on 2024-06-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_transaction_total_items'),
        ('prof', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.userprofile'),
        ),
    ]
